name: khatadiary
description: Khata
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-257.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  cloud_firestore: ^4.6.0
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  firebase_storage: ^11.1.2
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  antdesign_icons: ^0.0.3
  getwidget:
  intl:
  connectivity_plus:
  lottie: ^2.3.2
  flutter_datetime_picker: ^1.5.1
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
